services:
  docs:
    image: touchstone_manager_local_docs
    container_name: touchstone_manager_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./touchstone_manager:/app/touchstone_manager:z
    ports:
      - '9000:9000'
    command: /start-docs
