volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: touchstone_manager_production_django
    volumes:
      - production_django_media:/app/touchstone_manager/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: touchstone_manager_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    restart: unless-stopped

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: touchstone_manager_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'
    restart: unless-stopped

  redis:
    image: docker.io/redis:6
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: touchstone_manager_production_celeryworker
    command: /start-celeryworker
    restart: unless-stopped

  celerybeat:
    <<: *django
    image: touchstone_manager_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: touchstone_manager_production_flower
    command: /start-flower
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: touchstone_manager_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    restart: unless-stopped
