# Generated by Django 5.0.4 on 2024-04-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsample',
            name='infiltrations',
            field=models.IntegerField(default=0, verbose_name='Number of infiltrations with Nanomaterial'),
        ),
    ]
