# Generated by Django 5.0.4 on 2024-04-23 14:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0003_measurement_measurement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_file',
            field=models.FileField(blank=True, default='', storage=django.core.files.storage.FileSystemStorage(location='/media/uploads'), upload_to='measurements/'),
            preserve_default=False,
        ),
    ]
