# Generated by Django 5.0.4 on 2024-04-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0004_alter_measurement_measurement_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'material', 'verbose_name_plural': 'materials'},
        ),
        migrations.AlterModelOptions(
            name='materialsample',
            options={'verbose_name': 'material sample', 'verbose_name_plural': 'material samples'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'measurement', 'verbose_name_plural': 'measurements'},
        ),
    ]
