# Generated by Django 5.0.4 on 2024-04-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0005_alter_material_options_alter_materialsample_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_file',
            field=models.FileField(blank=True, upload_to='measurements/'),
        ),
    ]
