# Generated by Django 5.0.4 on 2024-04-25 09:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0006_alter_measurement_measurement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/uploads'), upload_to='measurements/'),
        ),
    ]
