# Generated by Django 5.0.4 on 2024-04-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0008_alter_measurement_measurement_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='processing_status',
            field=models.BooleanField(default=False, verbose_name='Processing status'),
        ),
    ]
