# Generated by Django 5.0.4 on 2024-04-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0009_measurement_processing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='processing_status',
        ),
    ]
