# Generated by Django 5.0.4 on 2024-04-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0012_alter_material_created_alter_material_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='measurement_data',
            field=models.JSONField(default=dict),
        ),
    ]
