# Generated by Django 5.0.4 on 2024-04-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0013_measurement_measurement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='mean_s21',
            field=models.FloatField(default=0, editable=False, verbose_name='Mean S21 over frequency range'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_data',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
