# Generated by Django 5.0.4 on 2024-05-02 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0015_alter_measurement_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Measurement date'),
        ),
    ]
