# Generated by Django 5.0.4 on 2024-05-02 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0016_alter_measurement_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Initially set to the current date and time. Will be updated with the date and time from the imported file.', verbose_name='Measurement date and time'),
        ),
    ]
